name: c_cell_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.0
  url_launcher: ^6.1.10
  video_player: ^2.11.1
  youtube_player_iframe: ^6.0.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/assets/images/cultural/aaveg/
    - assets/assets/images/cultural/capriccio/
    - assets/assets/images/cultural/eminence/
    - assets/assets/images/cultural/finlogue/
    - assets/assets/images/cultural/imagination/
    - assets/assets/images/cultural/insignia/
    - assets/assets/images/cultural/lc/
    - assets/assets/images/cultural/mediacell/
    - assets/assets/images/cultural/rendition/
    - assets/assets/images/cultural/sankalp/
    - assets/assets/images/cultural/vignette/
    - assets/assets/images/
    - assets/assets/images/viva/
    - assets/assets/images/plinth/
    - assets/assets/images/despo/
    - assets/assets/images/tech/astronomy/
    - assets/assets/images/tech/cipherclub/
    - assets/assets/images/tech/cybros/
    - assets/assets/images/tech/debsoc/
    - assets/assets/images/tech/ecell/
    - assets/assets/images/tech/phoenix/
    - assets/assets/images/tech/quizzinga/
    - assets/assets/images/sports/badminton/
    - assets/assets/images/sports/basketball/
    - assets/assets/images/sports/chess/
    - assets/assets/images/sports/cricket/
    - assets/assets/images/sports/football/
    - assets/assets/images/sports/kabaddi/
    - assets/assets/images/sports/lawn_tennis/
    - assets/assets/images/sports/squash/
    - assets/assets/images/sports/table_tennis/
    - assets/assets/images/sports/volleyball/
    - assets/assets/images/ted/
    - assets/assets/images/esummit/


   