// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkUPGltNoWpPHukAs9AHkxIpazNyOqSuw',
    appId: '1:1091655361396:web:33b90049e845a281ea0221',
    messagingSenderId: '1091655361396',
    projectId: 'c-cell-backend',
    authDomain: 'c-cell-backend.firebaseapp.com',
    storageBucket: 'c-cell-backend.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXj7jckrYPOvHM9WfuGxN9xhpv92i8K1E',
    appId: '1:1091655361396:android:d867989c54120553ea0221',
    messagingSenderId: '1091655361396',
    projectId: 'c-cell-backend',
    storageBucket: 'c-cell-backend.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBj4h8g6-Ae3GKDu4puMTSmozJmrDJb98M',
    appId: '1:1091655361396:ios:1f96277ea5b0354aea0221',
    messagingSenderId: '1091655361396',
    projectId: 'c-cell-backend',
    storageBucket: 'c-cell-backend.firebasestorage.app',
    iosClientId: '1091655361396-f2s2k3r30lpbb6f02nlmgm3lflkeu23t.apps.googleusercontent.com',
    iosBundleId: 'com.example.cCellApp',
  );
}
